// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3oaGoRNIvS2m9ObvNeVGKbDxnU72uGo',
    appId: '1:1021803741673:web:d083ce020b80a30f97cb78',
    messagingSenderId: '1021803741673',
    projectId: 'cat3-935e0',
    authDomain: 'cat3-935e0.firebaseapp.com',
    storageBucket: 'cat3-935e0.appspot.com',
    measurementId: 'G-NE4G2Q3PWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7H-BZOR9s58r7gsYfJH57OjcybKMiGhc',
    appId: '1:1021803741673:android:121b853bedb7a4f697cb78',
    messagingSenderId: '1021803741673',
    projectId: 'cat3-935e0',
    storageBucket: 'cat3-935e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC71DZaV6ygRJWRBEsm_Rsmd5d9FCvWFOM',
    appId: '1:1021803741673:ios:188e40a67db9885797cb78',
    messagingSenderId: '1021803741673',
    projectId: 'cat3-935e0',
    storageBucket: 'cat3-935e0.appspot.com',
    iosBundleId: 'com.example.kijuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC71DZaV6ygRJWRBEsm_Rsmd5d9FCvWFOM',
    appId: '1:1021803741673:ios:188e40a67db9885797cb78',
    messagingSenderId: '1021803741673',
    projectId: 'cat3-935e0',
    storageBucket: 'cat3-935e0.appspot.com',
    iosBundleId: 'com.example.kijuh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy3oaGoRNIvS2m9ObvNeVGKbDxnU72uGo',
    appId: '1:1021803741673:web:6bf906742eeea63097cb78',
    messagingSenderId: '1021803741673',
    projectId: 'cat3-935e0',
    authDomain: 'cat3-935e0.firebaseapp.com',
    storageBucket: 'cat3-935e0.appspot.com',
    measurementId: 'G-QQ3KP263ZM',
  );
}
